/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodega.GUI;
import bodega.Bodega;
import bodega.IEstoque;
import bodega.EstoqueVector;
import bodega.EstoqueArray;
import bodega.Produto;
import bodega.GerenciadorDeArquivo;
import bodega.exception.PNEexception;
import bodega.exception.QIexception;
import java.io.*;

/**
 *
 * @author Renato Marques
 */
public class Janela extends javax.swing.JFrame {
    Bodega bodega;
    IEstoque estoque;
    boolean focoEmEstoque;
    File arquivo;
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        setLocationRelativeTo(null);
        estoque = new EstoqueArray();
        bodega = new Bodega(estoque);
        listaEstoque.setListaProdutos(bodega);
        listaFalta.setListaProdutos(bodega);
        painelCadastro.setBodega(bodega);
        painelCadastro.setListaEstoque(listaEstoque);
        painelCadastro.setListaFalta(listaFalta);
        focoEmEstoque = true;
        arquivo = new File("dados.txt");
        GerenciadorDeArquivo.carregarBodega(arquivo, bodega);
        painelCadastro.atualizarListas();
        painelCadastro.setArquivo(arquivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEstoque = new java.awt.Label();
        labelFalta = new java.awt.Label();
        botaoRemover = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelConsulta = new bodega.GUI.painelConsulta();
        painelCadastro = new bodega.GUI.painelCadastro();
        painelVenda = new javax.swing.JPanel();
        labelVender = new java.awt.Label();
        textoVender = new javax.swing.JTextField();
        botaoVender = new javax.swing.JButton();
        labelEstocar = new java.awt.Label();
        textoEstocar = new javax.swing.JTextField();
        botaoEstocar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEstoque = new bodega.GUI.JListaBodegaEstoque<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFalta = new bodega.GUI.JListaBodegaFalta<>();
        textoBusca = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercearia do Seu Encrenca");

        labelEstoque.setText("Estoque");

        labelFalta.setText("Em falta");

        botaoRemover.setText("Remover Produto");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        jTabbedPane1.addTab("Consultar", painelConsulta);
        jTabbedPane1.addTab("Cadastrar", painelCadastro);

        labelVender.setText("Vender produto");

        textoVender.setText("00");

        botaoVender.setText("Vender");
        botaoVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderActionPerformed(evt);
            }
        });

        labelEstocar.setName(""); // NOI18N
        labelEstocar.setText("Estocar produto");

        textoEstocar.setText("00");

        botaoEstocar.setText("Estocar");
        botaoEstocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelVendaLayout = new javax.swing.GroupLayout(painelVenda);
        painelVenda.setLayout(painelVendaLayout);
        painelVendaLayout.setHorizontalGroup(
            painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelVendaLayout.createSequentialGroup()
                        .addComponent(textoVender, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVender))
                    .addComponent(labelEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelVendaLayout.createSequentialGroup()
                        .addComponent(textoEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEstocar)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        painelVendaLayout.setVerticalGroup(
            painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEstocar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vender/Estocar", painelVenda);

        listaEstoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaEstoqueFocusGained(evt);
            }
        });
        listaEstoque.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEstoqueValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaEstoque);

        listaFalta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaFaltaFocusGained(evt);
            }
        });
        listaFalta.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaFaltaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaFalta);

        textoBusca.setText("Código");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        label1.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(botaoRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(textoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(labelFalta, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFalta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(17, 17, 17)
                        .addComponent(botaoRemover)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBuscar)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderActionPerformed
        // TODO add your handling code here:
        Produto produto;
        if (focoEmEstoque) {
            produto = (Produto) listaEstoque.getSelectedValue();
        } else {
            produto = (Produto) listaFalta.getSelectedValue();
        }
        if (produto != null) {
            int n = Integer.valueOf(textoVender.getText());
            try {
                bodega.venderProduto(produto.getCodigo(), n);
                GerenciadorDeArquivo.salvarBodega(arquivo, bodega);
                painelCadastro.atualizarListas();
            } catch (PNEexception | QIexception e) {
                System.out.println(e.getMessage());
                ExceptionWindow aviso = new ExceptionWindow(e, this, true);
                aviso.setVisible(true);
            }
        }
    }//GEN-LAST:event_botaoVenderActionPerformed

    private void listaEstoqueValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEstoqueValueChanged
        // TODO add your handling code here:
        Produto produto = (Produto) listaEstoque.getSelectedValue();
        painelConsulta.setProduto(produto);
    }//GEN-LAST:event_listaEstoqueValueChanged

    private void listaFaltaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaFaltaValueChanged
        // TODO add your handling code here:
        Produto produto = (Produto) listaFalta.getSelectedValue();
        painelConsulta.setProduto(produto);
    }//GEN-LAST:event_listaFaltaValueChanged

    private void listaEstoqueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaEstoqueFocusGained
        // TODO add your handling code here:
        Produto produto = (Produto) listaEstoque.getSelectedValue();
        painelConsulta.setProduto(produto);
        focoEmEstoque = true;
    }//GEN-LAST:event_listaEstoqueFocusGained

    private void listaFaltaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaFaltaFocusGained
        // TODO add your handling code here:
        Produto produto = (Produto) listaFalta.getSelectedValue();
        painelConsulta.setProduto(produto);
        focoEmEstoque = false;
    }//GEN-LAST:event_listaFaltaFocusGained

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        // TODO add your handling code here:
        Produto produto;
        if (focoEmEstoque) {
            produto = (Produto) listaEstoque.getSelectedValue();
        } else {
            produto = (Produto) listaFalta.getSelectedValue();
        }
        if (produto != null) {
            try {
                bodega.removerProduto(produto.getCodigo());
                GerenciadorDeArquivo.salvarBodega(arquivo, bodega);
                painelCadastro.atualizarListas();
            } catch (PNEexception e) {
                System.out.println(e.getMessage());
                ExceptionWindow aviso = new ExceptionWindow(e, null, true);
                aviso.setVisible(true);
            }
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoEstocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstocarActionPerformed
        // TODO add your handling code here:
        Produto produto;
        if (focoEmEstoque) {
            produto = (Produto) listaEstoque.getSelectedValue();
        } else {
            produto = (Produto) listaFalta.getSelectedValue();
        }
        if (produto != null) {
            int n = Integer.valueOf(textoEstocar.getText());
            try {
                bodega.estocarProduto(produto.getCodigo(), n);
                GerenciadorDeArquivo.salvarBodega(arquivo,bodega);
                painelCadastro.atualizarListas();
            } catch (PNEexception e) {
                System.out.println(e.getMessage());
                ExceptionWindow aviso = new ExceptionWindow(e, null, true);
                aviso.setVisible(true);
            }
        }
    }//GEN-LAST:event_botaoEstocarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = textoBusca.getText();
        try {
            Produto produto = bodega.consultarProduto(codigo);
            if (produto.getQuantidade() > 0) {
                listaEstoque.setSelectedValue(produto, true);
                listaEstoque.requestFocusInWindow();
            } else {
                listaFalta.setSelectedValue(produto, true);
                listaFalta.requestFocusInWindow();
            }
            jTabbedPane1.setSelectedIndex(0);
        } catch (PNEexception e) {
            ExceptionWindow aviso = new ExceptionWindow(e, null, true);
            aviso.setVisible(true);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEstocar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoVender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label labelEstocar;
    private java.awt.Label labelEstoque;
    private java.awt.Label labelFalta;
    private java.awt.Label labelVender;
    private bodega.GUI.JListaBodegaEstoque<Produto> listaEstoque;
    private bodega.GUI.JListaBodegaFalta<Produto> listaFalta;
    private bodega.GUI.painelCadastro painelCadastro;
    private bodega.GUI.painelConsulta painelConsulta;
    private javax.swing.JPanel painelVenda;
    private javax.swing.JTextField textoBusca;
    private javax.swing.JTextField textoEstocar;
    private javax.swing.JTextField textoVender;
    // End of variables declaration//GEN-END:variables
}
