/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodega.GUI;
//import bodega.IEstoque;
//import bodega.EstoqueVector;
import bodega.Produto;
import bodega.ProdutoPerecivel;
import bodega.Bodega;
import bodega.GerenciadorDeArquivo;
import java.io.*;
import bodega.exception.*;

/**
 *
 * @author Renato Marques
 */
public class painelCadastro extends javax.swing.JPanel {
    private Bodega bodega;
    private JListaBodegaEstoque listaEstoque;
    private JListaBodegaFalta listaFalta;
    private File arquivo;
    /**
     * Creates new form painelCadastro
     */
    public painelCadastro() {
        initComponents();
        bodega = null;
        listaEstoque = null;
        listaFalta = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNome = new javax.swing.JTextField();
        labelNome = new java.awt.Label();
        textoCodigo = new javax.swing.JTextField();
        labelCodigo = new java.awt.Label();
        textoPreco = new javax.swing.JTextField();
        labelPreco = new java.awt.Label();
        textoQuantidade = new javax.swing.JTextField();
        labelQuantidade = new java.awt.Label();
        checkBoxPerecivel = new javax.swing.JCheckBox();
        textoValidade = new javax.swing.JTextField();
        labelValidade = new java.awt.Label();
        botaoCadastrar = new javax.swing.JButton();

        setToolTipText("Cadastro");
        setName("Cadastro"); // NOI18N

        textoNome.setText("Nome");

        labelNome.setText("Nome do produto");

        textoCodigo.setText("Código");

        labelCodigo.setText("Código do Produto");

        textoPreco.setText("Preço");

        labelPreco.setText("Preço do produto");

        textoQuantidade.setText("Quantidade");

        labelQuantidade.setText("Quantidade do produto");

        checkBoxPerecivel.setText("Perecível");

        textoValidade.setText("Validade");

        labelValidade.setText("Validade");

        botaoCadastrar.setText("Cadastrar Novo");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCodigo)
                            .addComponent(textoNome))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoCadastrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxPerecivel)
                                .addGap(28, 28, 28)
                                .addComponent(labelValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxPerecivel)
                    .addComponent(labelValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
        Produto produto;
        if (checkBoxPerecivel.isSelected()) {
            produto = new ProdutoPerecivel(textoCodigo.getText());
            ((ProdutoPerecivel) produto).setValidade(textoValidade.getText());
        } else {
            produto = new Produto(textoCodigo.getText());
        }
        produto.setNome(textoNome.getText());
        try {
            produto.setPreco(textoPreco.getText());
            produto.setQuantidade(textoQuantidade.getText());
            bodega.adicionarProduto(produto);
            GerenciadorDeArquivo.salvarBodega(arquivo, bodega);
            atualizarListas();
        } catch (FIexception | PJCexception e) {
            System.out.println(e.getMessage());
            ExceptionWindow aviso = new ExceptionWindow(e, null, true);
            aviso.setVisible(true);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    public void atualizarListas() {
        listaEstoque.setListaProdutos(bodega);
        listaFalta.setListaProdutos(bodega);
    }    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Bodega getBodega() {
        return bodega;
    }
    public void setListaEstoque(JListaBodegaEstoque lista) {
        this.listaEstoque = lista;
    }
    public javax.swing.JList getListaEstoque() {
        return (javax.swing.JList) listaEstoque;
    }
    public void setListaFalta(JListaBodegaFalta lista) {
        this.listaFalta = lista;
    }
    public javax.swing.JList getListaFalta() {
        return (javax.swing.JList) listaFalta;
    }
    public void setArquivo(File arquivo) {
        this.arquivo = arquivo;
    }
    public File getArquivo() {
        return arquivo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JCheckBox checkBoxPerecivel;
    private java.awt.Label labelCodigo;
    private java.awt.Label labelNome;
    private java.awt.Label labelPreco;
    private java.awt.Label labelQuantidade;
    private java.awt.Label labelValidade;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoPreco;
    private javax.swing.JTextField textoQuantidade;
    private javax.swing.JTextField textoValidade;
    // End of variables declaration//GEN-END:variables
}
